server:
  port: 18080




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      # 可以使用用户名密码
      # user:password@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: test-gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: path_route_1
          uri: lb://test-eureka-client
          order: 0
          predicates:
            - name: Path
              args:
                - p0: /user/**
        - id: path_route_2
          uri: lb://test-eureka-client1
          order: 0
          predicates:
            - name: Path
              args:
                - p0: /test/**
            - Host=127.0.0.1:18080