server:
  port: 12931


spring:
  application:
    name: test-zipkin-consumer
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      rate: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      # 可以使用用户名密码
      # user:password@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true