


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      # 可以使用用户名密码
      # user:password@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8083

spring:
  application:
    name: test-eureka-client


management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - refresh